language: node_js
node_js:
  - '4'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
script:  
  - 'grunt build'
after_script:
  - cd dist
  - git init
  - git config user.name "zhang-yuan"
  - git config user.email "yzgg1020@gmail.com"
  - git add .
  - git commit -m "update pages"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: github.com/zhang-yuan/angular-weather.git
    - secure: "g8yzP8jscHSGLhuPsyskjEIBYki4YIRA8fGEc001X3+8mgdvgVUwYlSxm1bVqqISRvBmuNo71gVTOBENjLJf+E3o8gTur6KMjunztNO2j+QWC4k2oId6XoxbNfgWMRTZfM1rDF0R7QnYmWlf4WDEQlxZfTpTrAuNgXjLmo5UJtE="
